name: upsun-ddev-automated-test-target
type: drupal10
docroot: web
php_version: "8.4"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.6"
hooks:
    post-start:
        - composer: install
use_dns_when_possible: true
composer_version: "2"
# web environment config is in .ddev/.env
#web_environment:
#    - PLATFORM_PROJECT=5dxxbe2vazzdo
#    - PLATFORM_ENVIRONMENT=pull
#    - PLATFORM_APP=d10simple
#    - PLATFORM_PRIMARY_RELATIONSHIP=mariadb

corepack_enable: false
